import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { resolve } from "node:path";

function parseArgs(argv) {
  const options = {
    appDomain: "app.birthhub360.com",
    apiDomain: "api.birthhub360.com",
    caddyEmail: "ops@birthhub360.com",
    force: false,
    input: ".env.vps.example",
    output: ".env.vps"
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    switch (arg) {
      case "--input":
        options.input = argv[index + 1] ?? options.input;
        index += 1;
        break;
      case "--output":
        options.output = argv[index + 1] ?? options.output;
        index += 1;
        break;
      case "--app-domain":
        options.appDomain = argv[index + 1] ?? options.appDomain;
        index += 1;
        break;
      case "--api-domain":
        options.apiDomain = argv[index + 1] ?? options.apiDomain;
        index += 1;
        break;
      case "--caddy-email":
        options.caddyEmail = argv[index + 1] ?? options.caddyEmail;
        index += 1;
        break;
      case "--force":
        options.force = true;
        break;
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return options;
}

function randomHex(bytes = 32) {
  return randomBytes(bytes).toString("hex");
}

function randomAlphaNumeric(length) {
  const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  const source = randomBytes(length * 2);
  let output = "";

  for (const byte of source) {
    output += alphabet[byte % alphabet.length] ?? "";
    if (output.length >= length) {
      return output.slice(0, length);
    }
  }

  return output.slice(0, length);
}

function replaceLine(content, key, value) {
  const pattern = new RegExp(`^${key}=.*$`, "m");
  return content.replace(pattern, `${key}=${value}`);
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  const inputPath = resolve(process.cwd(), options.input);
  const outputPath = resolve(process.cwd(), options.output);

  if (!existsSync(inputPath)) {
    throw new Error(`Input file not found: ${inputPath}`);
  }

  if (existsSync(outputPath) && !options.force) {
    throw new Error(`Output file already exists: ${outputPath}. Use --force to overwrite.`);
  }

  const appUrl = `https://${options.appDomain}`;
  const apiUrl = `https://${options.apiDomain}`;
  let content = readFileSync(inputPath, "utf8");

  content = replaceLine(content, "APP_DOMAIN", options.appDomain);
  content = replaceLine(content, "API_DOMAIN", options.apiDomain);
  content = replaceLine(content, "CADDY_EMAIL", options.caddyEmail);
  content = replaceLine(content, "NEXT_PUBLIC_APP_URL", appUrl);
  content = replaceLine(content, "NEXT_PUBLIC_API_URL", apiUrl);
  content = replaceLine(content, "WEB_BASE_URL", appUrl);
  content = replaceLine(content, "API_CORS_ORIGINS", appUrl);
  content = replaceLine(content, "EMAIL_FROM_ADDRESS", `noreply@${options.appDomain.replace(/^app\./, "")}`);
  content = replaceLine(content, "NEXTAUTH_SECRET", randomHex(32));
  content = replaceLine(content, "SESSION_SECRET", randomHex(32));
  content = replaceLine(content, "AUTH_MFA_ENCRYPTION_KEY", randomHex(32));
  content = replaceLine(content, "JOB_HMAC_GLOBAL_SECRET", randomHex(32));
  content = replaceLine(content, "STRIPE_SECRET_KEY", `sk_live_${randomAlphaNumeric(48)}`);
  content = replaceLine(content, "STRIPE_WEBHOOK_SECRET", `whsec_${randomAlphaNumeric(48)}`);
  content = replaceLine(content, "STRIPE_SUCCESS_URL", `${appUrl}/billing/success`);
  content = replaceLine(content, "STRIPE_CANCEL_URL", `${appUrl}/billing/cancel`);
  content = replaceLine(content, "STRIPE_PORTAL_RETURN_URL", `${appUrl}/settings/billing`);

  const banner = [
    "# Generated by scripts/ops/generate-vps-env.mjs",
    "# Internal secrets were materialized locally.",
    "# Replace DATABASE_URL, DIRECT_DATABASE_URL, REDIS_URL, STRIPE_* and observability fields with real provider values before launch.",
    ""
  ].join("\n");

  writeFileSync(outputPath, `${banner}${content}`, "utf8");
  console.log(`Created ${outputPath}`);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
